version: "3.6"
# NOTE: An on-site instance of etcd to carry on LB's configuration
services:
  etcd:
    image: kontena/etcd:2.3.3
    command: --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd:2379

  # NOTE: An instance of LB, that is intended for SSL/TLS validations
  lb:
    build: .
    command: -log-level=debug
    environment:
      ETCD_NODE: "etcd"
      KONTENA_SERVICE_NAME: "lb"
      KONTENA_LB_HEALTH_URI: "/health"
      KONTENA_LB_SSL_CIPHERS: ECDHE-RSA-AES128-GCM-SHA256
      KONTENA_LB_CUSTOM_SETTINGS: |
        option dontlognull
      KONTENA_LB_GLOBAL_SETTINGS: |
        ssl-default-bind-options force-tlsv12
      ACME_CHALLENGE_LoqXcYV8q5ONbJQxbmR7SCTNo3tiAXDfowyjxAjEuX0: |
        LoqXcYV8q5ONbJQxbmR7SCTNo3tiAXDfowyjxAjEuX0.9jg46WB3rR_AHD-EBXdN7cBkH1WOu0tA3M9fm21mqTI

      SSL_CERT_test1: |
        -----BEGIN CERTIFICATE-----
        MIIC9TCCAd2gAwIBAgIJAK94fUzfHt1pMA0GCSqGSIb3DQEBCwUAMBExDzANBgNV
        BAMMBnRlc3QtMTAeFw0xNzEwMjYxMDA5MDNaFw0yMDA3MjIxMDA5MDNaMBExDzAN
        BgNVBAMMBnRlc3QtMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMP9
        6ym6ptYHFh0o2aoGqTUL+Di+BYNMTDA2CciHtMPL7/SqdtS8Dej0hguyiee37D07
        b+Lo9I4/wBYVtCIUrDqqQvYwkAsUbZKD+nXWalfpSGtt3iFT4nVCg833yK6b6/JN
        TqpMmruMjn9sadzEAxabHU9at/j9ZCLrQBdgrGRhGJcCgPSc3jTLAEz5gf45F3DO
        vD/4aZYCsjS2qFHvtzFBP8pVqRP9CiXvCw/tuwN7wA7wBeJ185JPax8FfSELaDbZ
        Yd63GEVVCmM87HS8faCCbffmaciPoHPl8TyM3+FaGSot3HT6VLnkVFeQR470nKxT
        0PX/iSD++b05l8GGjKECAwEAAaNQME4wHQYDVR0OBBYEFLJn8DEv3K4ISyzh8Du5
        GnOeT6WIMB8GA1UdIwQYMBaAFLJn8DEv3K4ISyzh8Du5GnOeT6WIMAwGA1UdEwQF
        MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAL/KI42JqasFCofB+ii4L6qodHohhaw1
        tso6YQTSwvwYDG/tmjUdIRB3W2Vi4eUUHjhH0/CJk/jZaTOpQrC/Kd89gcQr+UzM
        uXx2bDGMp6VszE9wFPBpczoPndmc9ExPijbtOD4Q5NRpOgxs55JoVLyOEijvSfEn
        dQetBiLeudiYkQT89APysveqkj2WojK6H3Obvns9bZ5HlnGcWP71ttY1/HyIMd1P
        2d10zFA66rriEwlcsOTKuusJ0y2OUOA6Fzi3v1vInDvx21QzLX3NMUtqn3t5qtto
        UQCkJrk2TE6mrL92igBV/+ckB5cGvJ5L8viyvijezX3xjOzn9JGhFhA=
        -----END CERTIFICATE-----
        -----BEGIN PRIVATE KEY-----
        MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDD/espuqbWBxYd
        KNmqBqk1C/g4vgWDTEwwNgnIh7TDy+/0qnbUvA3o9IYLsonnt+w9O2/i6PSOP8AW
        FbQiFKw6qkL2MJALFG2Sg/p11mpX6Uhrbd4hU+J1QoPN98ium+vyTU6qTJq7jI5/
        bGncxAMWmx1PWrf4/WQi60AXYKxkYRiXAoD0nN40ywBM+YH+ORdwzrw/+GmWArI0
        tqhR77cxQT/KVakT/Qol7wsP7bsDe8AO8AXidfOST2sfBX0hC2g22WHetxhFVQpj
        POx0vH2ggm335mnIj6Bz5fE8jN/hWhkqLdx0+lS55FRXkEeO9JysU9D1/4kg/vm9
        OZfBhoyhAgMBAAECggEBAIm3y93npUHxes2EneZGhfGbdpFQnQkUvNiHsDozeYa3
        r+YpPhTgC5os8GAZ1aN4bszcDhPRA79M9onOOGRWSGt0plbd6umOMixpBr50qwcZ
        CmVKr3KVwiQJWBqLyX1AXPxG7EboSzYMXzkUkhKpvU3OMztGkM2qKAoNalzC9oAV
        KdxTp52bG2iekBNj1b839jl57eRmJsGcAcRXMtxblvak84LEfPhnXSUp0nhhTHD2
        Dr+jvxF+q8TbIyf+StKppi3KmHliSr1qqLKC3+9qsHRCw0REnqOTJ04QHjo3QjUU
        3Rlpal/b9yFyxT5o9+doQKKU7EISRwERfn2POLOO+pECgYEA916+BKBF8jq4Yghu
        G+b/zEZpeVeRYbPnxCgqrqI83+tistMbJxI1cHch7VLl6hVngD+U4BOnXRUGwHmG
        UxH7mzurX7ULJfoTSpN+4yMsd9kuBvlzoqgzaxg6Cl1adRQJUcaf1Ki3DN7ToFMU
        WRQdFNaVrEvEA5VefPeAk+utMLUCgYEAytRRhDMafqpFzVj/LSvYDVuMQCHMqRpJ
        S71HyW+qunyhzlYSUqk9IHWLDIET0bIZhVa4yThvnv3nekJ+OGPsci1Yi3uOziJK
        Oedv+UMu83p/Lo7pgMlfjj8EjOtAd9d3Sn35YIH8hQDF2iyCFABaVFCFwMkVEE8A
        rZu8naT8m70CgYEAz5kbLxaynM7a3qrkfVYnZm/RJJxwzeYFo4FyEIznOaR5eEni
        h6+oWXIhbuIbQZAlBGRXtJXJ5zw2JmHWcPCuj2BMOk3dxUlR10xhOI3US+Bf2EqQ
        2Pj/7eivDPO7bnYaPB7NE9Nji9GVGP+gHAHdRhewFKChJ8C7Q3US2xD2j+ECgYEA
        k/aZVOh23opWi3vuA0TlwrDTOoGtrHrpl2AIe3GDybFb1ItDqJufZQt6mW+cRrA3
        H+dovBn4i7LL54uUSozSk2RzIKXNQqEPJvin3d3d5W6qUwucWgANPlbIegiwKfy8
        IFKP1pBc56Xtr8AiUHcFblajjETkodYQN5XR3erbAL0CgYEA6KfaCQkIe3NbTN6H
        o1hmwFgF2p4gjM202GwR6A4f4uvgrmnd76YDTmZidFbGfFw5igB3Gfisjd9nthtZ
        +NUq8hr7lx+ZJ413LyF/9CQAQn1l5BuIpcDGDirm8od4nZvg53qN1Q8AqEzZFcMw
        IJepvjbc/iTWfYqrWuod1wcBU5A=
        -----END PRIVATE KEY-----
      SSL_CERTS: |
        -----BEGIN CERTIFICATE-----
        MIIC+zCCAeOgAwIBAgIJAJXVkdCXj6aqMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
        BAMMCWxvY2FsaG9zdDAeFw0xNzEwMjYwOTA1MjdaFw0yMDA3MjIwOTA1MjdaMBQx
        EjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
        ggEBAKzwoA0yPoG+VqJr4F69Iaif0SumXfgt16zfaJJYKYqCOoq9qVjX89jA6CQ5
        q+zn7066ihK1pFHA2T+Be7rMRo76p1VG2YW1NQ1Dj6LENVqgJqqVaVJbe67pvTLz
        dzZRLbjjpRV8M83CiSYTm+p53qBAsvl5DWQBRIJwK45LIi5kz7UxqI+R+SPLQJqC
        4+U8TDDJ1pEdZJ4qlb9eJuP8l6TXtLrSuaLzhTPg08JGigAag39Mg1F2nkNSCI6w
        R7qGw3EhWgHjhsNCS/jP/w+JKQbQyuDuO5bYCVI9zBGbMtpP6xeDKDhmDGTguvYN
        +opSq1Aija93kk6N9ueFxlY+y4UCAwEAAaNQME4wHQYDVR0OBBYEFMZSiX50Bls8
        j8j66O0FXr/ZWtYFMB8GA1UdIwQYMBaAFMZSiX50Bls8j8j66O0FXr/ZWtYFMAwG
        A1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBABhw+3Pm0nLhwEAtmUscH0bx
        XenjMxP5F3GxIj8eJfIWO4fXS/LIXTcM0ghKbm6q0zdBVra/nLMvrjyxYJlOqn04
        WyvBLH2EXjvIl8Bl/JLvLlddJ4gCfu5zW4d7Bs2+MBPVvfzzfFHKlmua5GbNxPoM
        hbVhZfWWqvN493mBOLE1j/1Bgch4zZGwJefP1+YuI2QHTDk8XmtBkBWymRAD4hBa
        8Yg+XLBHfcGeqpIiCRXnTlQuxabmZlDmwh/M+Cxiac676z76EN62+zcAgd1NpAO6
        BRkJQadwDC4A9ogEkBYXwG0X9/+ZB6CzG4Vx+vdSupkFMp9b0z2vcodfO39KONg=
        -----END CERTIFICATE-----
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCs8KANMj6Bvlai
        a+BevSGon9Erpl34Ldes32iSWCmKgjqKvalY1/PYwOgkOavs5+9OuooStaRRwNk/
        gXu6zEaO+qdVRtmFtTUNQ4+ixDVaoCaqlWlSW3uu6b0y83c2US2446UVfDPNwokm
        E5vqed6gQLL5eQ1kAUSCcCuOSyIuZM+1MaiPkfkjy0CaguPlPEwwydaRHWSeKpW/
        Xibj/Jek17S60rmi84Uz4NPCRooAGoN/TINRdp5DUgiOsEe6hsNxIVoB44bDQkv4
        z/8PiSkG0Mrg7juW2AlSPcwRmzLaT+sXgyg4Zgxk4Lr2DfqKUqtQIo2vd5JOjfbn
        hcZWPsuFAgMBAAECggEAF2tikUbrlhBblRU8xjeglkBGSD34XcJ/gYajl6XewkYO
        fXlftItSF1lQVo+Ey8lA7A1w40W74eJWyTXUtqAxMe2ZuX+lt2iprYknq2gcvZAQ
        jGs9XwzKfA5lM8Aqta1anr4dPgKa1VNx1Tk0lRU548O/OO9+s7tENtHP5C4ii9uc
        EPTq8V0vm2VbZOW17Yfw6a7RlxEvHP3JorECUvQwgYUSwgjQ2LLBEsCVpWo9w3z6
        ffCbz9X6JJ8DeqKS524o1RMyifdGgynnB8zVYsLwnEPTp5mFDec5+jWLjTCO/m+e
        IiGuaeeUBSG+oLREDjhw+bkb3wY/MGZsC546tOsKRQKBgQDW4XhAA5ES5ZNG5yMC
        rvBF1qtHFXxd060kn7Ndz6oGkGuZ99G0+NXHuaSP3CqEuOYdg2NS2LX32EHhwnFF
        /uRR4UKHLKJL/Ai1jk8/L+7sQSezzzW/Mek5v4lxH9hflfR2zH99Qb5Zemld5I1f
        rBuEGvLUTfv1nGCD+5PPZWnwCwKBgQDOCJGiSV4gozTO+Uq9yIuWJ9JB5JpM6IVF
        CNxmBseFLNZcnKb/Bl/NTH87Y7uk4r6nQ0VMfwv+dwd+wa/y0eau92T+PXo2sspp
        vlwGPP5RrcsDpOl5jiT022/MI9ybgnjNWFE3bA4DuCNua49LRTxW8Q1Leiu740EU
        XcnrFMecrwKBgBX5bMCvHLDgBVWk4XGuzid2MoHMcrFtqjEqm78mM28EadyO+UUW
        hVYtZ+TGURrNhcrS2t9oBgPYe7RInCjaTiMJdDI6oEZA+esHKJd/oWFLsHG06Pwq
        cH1VVwrYhNoRjbRwaUE37e1clVXiv4pfIVk7IEYRy4hse3pDyfPVnSXNAoGBAKX4
        7SiopbTxBId+9yCvPxM0/QGr4Ej4PvN/0dw2td+oYP62CykBv4coio4TJ4QKTL99
        R4P6DHVu+ZC5Ar4/LO/hx2+vopYRrVFF0egMlmrB7/r9jD8prMe7RfJTKVH05s+0
        x6g32YpReelnqEVgft0izizxO+3dgf2gGBrR4INtAoGAIC3t93txnUNlRu0He6mL
        alFBjeDBl80/bhM74Aqo0veAHHwNZw5xg4dSwe5ydv5Ei6fLl5A4mqInPfRJhEVe
        WpuPlhWSprWv6eunCzG1huWrda4/0aXiOc/n5mdHAZ6v7sBrKEWWSiZlZ6+jay5M
        adNVFeXMFuwC0t7u0nUTQss=
        -----END PRIVATE KEY-----
        -----BEGIN CERTIFICATE-----
        MIIDQzCCAiugAwIBAgIJAOU1G4gSj6nYMA0GCSqGSIb3DQEBCwUAMDgxCjAIBgNV
        BAMMASoxHTAbBgNVBAoMFE15IENvbXBhbnkgTmFtZSBMVEQuMQswCQYDVQQGEwJV
        UzAeFw0xNjA2MDMwNjU2MTdaFw0xOTA1MTkwNjU2MTdaMDgxCjAIBgNVBAMMASox
        HTAbBgNVBAoMFE15IENvbXBhbnkgTmFtZSBMVEQuMQswCQYDVQQGEwJVUzCCASIw
        DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK4TvlMa3/9YK1aLSWBh1QPGulQd
        aYLoCSDYoTMv0YOO4lLDPBkU6fzjwWX44nesBjUmN61QxBkpGNTs9x6pNvd4YI7N
        arhxSljROf42vNWkoVKl0Ls3fgUxMAcbFYf38i5PLzVLebsIZR2+sVe6QdwWAame
        nhlEE1ubnx46xROCTLkjfzLlYdSJBNPx8gKovgf31gWU9dtVrdkBclHmglspXZt0
        removed_to_invalidate_certs
        Qi89hSFKjDTFeovydxbaOR3k5PKqOFD1Lou9Ho87TeLBNNYkA16IdJ63dLMCAwEA
        AaNQME4wHQYDVR0OBBYEFNO0I5ogOcgUbWmaBj1hA8qt7F0rMB8GA1UdIwQYMBaA
        FNO0I5ogOcgUbWmaBj1hA8qt7F0rMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEL
        BQADggEBAHpJiP8ZblJmEuSP0lAJRovTPGhKZA4Pgpa9zimETCruBTkTZyCcNwD3
        htHgrqkCieoV5RK5juyHVQo5GiVptcWxVSuGgr9tKtWTYlfB0xkRRT9No0bjT9J8
        cGTZm+lZyQ85AuwOPSe1wFUDPuLu8xJVPJoIeDNaKqjZleVZUNafPSKRWhi0X6rt
        JmwgQdUBqRgZYHL6Zpcr2E5oyc4tL10pYcIQchyDHg0IHyVb/xz072RFRKj0zP4A
        2wVolufLJCFVbc8g1vEDgRjsuGLN55bJ0CTsn14GcOLsBntqKYyKm6lwV3+dDRM/
        AacJXcMY+aRv/l5fNl0oMRcZpRr3gew=
        -----END CERTIFICATE-----
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuE75TGt//WCtW
        i0lgYdUDxrpUHWmC6Akg2KEzL9GDjuJSwzwZFOn848Fl+OJ3rAY1JjetUMQZKRjU
        7PceqTb3eGCOzWq4cUpY0Tn+NrzVpKFSpdC7N34FMTAHGxWH9/IuTy81S3m7CGUd
        vrFXukHcFgGpnp4ZRBNbm58eOsUTgky5I38y5WHUiQTT8fICqL4H99YFlPXbVa3Z
        AXJR5oJbKV2bdAnWkLO2NbpK72+VsjV1wiZXMr44aQ67dZwdZZ11eWZyjfcrXQ2z
        f6NxhRlzJg/ItkIvPYUhSow0xXqL8ncW2jkd5OTyqjhQ9S6LvR6PO03iwTTWJANe
        iHSet3SzAgMBAAECggEBAIo8y4ubb/6Kuf/EJMURa+PP0PAzWzLFqVoYLgtEEhFz
        Sm+G8xbH8PkOtOqRtuZqCZPzgYt09AU3Ca0tcSE8J5ZmVeeRYQqPjQbzQCaMuXC/
        iAzl+NhzvPPKl+VMsNCFKiF0aHzeLxFEHWh9or+T/fEU2MUmXU6bLPQ2pSmQaiiO
        pEDH0d5xuWP90LgfPJoKcBlai140Ml+gLTnTfBIElQg06TiSSQM2yVfF5sz7Sbe2
        pjTqyVNDP01pBoUpR2BAB/JbeqaWM8jnnIi+35uE1kvttq97T3WfBHcW6j7RN5N8
        HmsxDcG8GPV/6Z7j5ZGHACsQsI6bSbXdFACDOM4e74ECgYEA54I0Tut4NBlI0RkD
        removed_to_invalidate_certs
        v4ZWS2blGUguFGybgyaeJemqW+CdcBTzglsOXDi4C1NrLqgX3+c8PULsN0wns5B0
        KoRU+oBrK/coPT1/J0cnLWqdfcMCgYEAwH4o7HIk8zour+7f1fNB7642dbndCQut
        c+Kf48WDQpCOLCHvHujOY92XCVkEVP63lsc/JJCr9s8fxnUIX2z5/bwpKZn4f4Zy
        fzwslzIWCLXAyPTHaux9u+8vtJRTPaQ0YYOigSn1xdLu5Xu/761jStQTs1i4MN3P
        VI68gffWDlECgYEA4FhAAn6TRMF/3AmGqOGbJeibbaACp8FAe4x5qJhIz7Ekau0R
        gRrAds6IgQ2O1w0dWTXmBsRdriOSxz/+4If5FibHOoHFDcvVw/lnZkwS5+g6CUR0
        Wc2Nk/bu+yLCijsgr7ywlplEua2WB5+jwxPsGbjaoodnujjfAJwmLg/UQOsCgYAq
        OAF1yps8FZjD0ZqabF4b2ZPsQjWulDcY4a274Ugmw1nLaC3wE5Og56sGy9VdZviR
        Q2Yf+PMekNMhTe3mMBqsgiZtD24nWi+mpGYLS1r10hdUfAt48iGppI5MBvQy4t7y
        PFLaDX/wQZFQF9JDGT5b3SPtBBpx7VRZ8Wx6/Qaf4QKBgDN7nX2YAt0t60kFzL2V
        hdSuTbjdDTNYALHrPlOiUV0LXOWSpeJpjI7BbFYbwEXHWyJ6XJs/uS1pX9AfglXY
        KNjEBaOzuTkyIX1THmpnt9417EVQeCYYbMvnKvzhVi32Enr5p8Y5t8i75lrfpvta
        XxGBmgtsa++i6DvXUp/Jv1Xy
        -----END PRIVATE KEY-----
    links:
      - service-a
      - service-b
      - service-c
      - etcd

  # NOTE: An instance of LB, that is intended for a few edge cases validations.
  lb_no_health:
    build: .
    command: -log-level=debug
    environment:
      - KONTENA_SERVICE_NAME=lb_no_health
      - ETCD_NODE=etcd

  # NOTE: A 'service-a' instance of the test server
  service-a:
    build: test/server
    container_name: service-a
    hostname: service-a

  # NOTE: A 'service-b' instance of the test server
  service-b:
    build: test/server
    container_name: service-b
    hostname: service-b

  # NOTE: A 'service-c' instance of the test server
  service-c:
    build: test/server
    container_name: service-c
    hostname: service-c

  # NOTE: An instance of the test helper, used to execute curl requests
  lbe:
    image: krates/toolbox:2.4.9-4
    command: -c "./build/test.sh"
    working_dir: /lbe
    volumes:
      - .:/lbe
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TRACE=${TRACE}
      - ETCDCTL_ENDPOINTS=http://etcd:2379
    links:
      - etcd
      - lb:test-1
      - lb:localhost
      - lb_no_health